version: "3"
services:
  bot:
    build:
      context: bot
      dockerfile: Dockerfile
    links:
      - bridge
    env_file:
      - .env
  bridge:
    build:
      context: bridge
      dockerfile: Dockerfile